#!/usr/bin/env python3
"""Build js/core/catalog.js from a Rebrickable catalogue database.

Usage: python3 tools/gen-catalog.py path/to/lego.sqlite
(the SQLite file ships with the `lego-oracle` npm package: npm pack lego-oracle)

For every part in the library it records the official name and, per colour, how many
sets released since 2015 contain it and how many pieces were produced in those sets.
That tells us (a) the part really exists in that colour and (b) how common, i.e. how
cheap, it is on the second-hand market.
"""
import json, sqlite3, subprocess, sys, os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
db = sqlite3.connect(sys.argv[1])
c = db.cursor()
ids = json.loads(subprocess.check_output(['node', os.path.join(root, 'tools/list-parts.mjs')], cwd=root))
c.execute("""create temp table pcx as SELECT ip.part_num part_num, ip.color_id color_id,
  COUNT(DISTINCT CASE WHEN s.year>=2015 THEN i.set_num END) ns, SUM(CASE WHEN s.year>=2015 THEN ip.quantity ELSE 0 END) q,
  COUNT(DISTINCT i.set_num) nsa, MAX(s.year) y1
  FROM inventory_parts ip JOIN inventories i ON ip.inventory_id=i.id JOIN sets s ON s.set_num=i.set_num
  WHERE ip.part_num IN (%s) GROUP BY 1,2""" % ','.join('?' * len(ids['all'])), ids['all'])
parts = {}
for pid in ids['all']:
    r = c.execute('select name, part_cat_id from parts where part_num=?', (pid,)).fetchone()
    if not r:
        print('!! missing in catalogue:', pid); continue
    cols = {}
    for col, ns, q, nsa, y1 in c.execute('select color_id, ns, q, nsa, y1 from pcx where part_num=?', (pid,)):
        cols[col] = [ns, q, nsa, y1]
    # minifig parts are mostly inventoried inside minifigs (not sets): count every inventory too
    if True:
        for col, n in c.execute("""select ip.color_id, count(distinct i.set_num) from inventory_parts ip join inventories i on ip.inventory_id=i.id
                                   where ip.part_num=? group by 1""", (pid,)):
            cols.setdefault(col, [0, 0, n, 0])
            cols[col][2] = max(cols[col][2], n)
    parts[pid] = {'name': r[0], 'colors': cols}
colors = {r[0]: r[1] for r in c.execute('select id, name from colors')}
used_colors = sorted({cc for v in ids['used'].values() for cc in v})
out = {
    'source': 'Rebrickable catalogue (via lego-oracle), sets 2015+ for commonness',
    'parts': parts,
    'colorNames': {k: colors[k] for k in used_colors},
}
with open(os.path.join(root, 'js/core/catalog.js'), 'w') as f:
    f.write('// GENERATED by tools/gen-catalog.py from the Rebrickable catalogue - do not edit by hand.\n')
    f.write('// parts[id].colors[rebrickableColorId] = [sets since 2015, pieces in those sets, sets ever, last year]\n')
    f.write('export const CATALOG = ' + json.dumps(out, separators=(',', ':')) + ';\n')
print('wrote', len(parts), 'parts')
